In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd 
import numpy as np

WARNING:tensorflow:From c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
# Load the trained model, scaler pickle, one hot
model=load_model('model.h5')

# load the encoder and scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo = pickle.load(file)
    
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)
    
with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:From c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [3]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [5]:
# Now when I'm giving this particular data, the first thing that I need to think is that how do I convert
# this particular value into numerical and this particular value into numerical. 
# So and then after that take all the numerical value and convert that into standard means.
# Scale down that particular value using standard scaler.
# That is the reason we have stored this in the form of pickle file.

In [6]:
# And now with respect to this new input data, you need to think, how can I probably take this particular
# data and perform a convert categorical features into numerical features?
# That is what you really need to think first of all.
# The second thing is, uh uh, how do you apply standard scaling?
# Right.
# And then how do you do the prediction with respect to the model?

In [7]:
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [8]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [11]:
# encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [12]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [13]:
# concatenate one hot encoded
input_df = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [14]:
# scaling the input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [15]:
# prediction churn
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 167ms/step

array([[0.04202289]], dtype=float32)

In [16]:
# prediction probability
prediction_proba = prediction[0][0]
prediction_proba

0.04202289

In [17]:
if prediction_proba > 0.5:
    print('The customer is likely to churn')
else:
    print('The customer is not likely to churn')

The customer is not likely to churn

In [ ]:
# 1] We trained our ANN model.
# 2] we calculate loss
# 3] we apply early stopping
# 4] we visualize data
# 5] we predict the output from input data