In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# EstimatedSalary was my output feature and remaining all columns are independant feature

# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [6]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [10]:
## Split the data in training and tetsing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
## Scale these features
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

##### ANN Regression Problem Statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [13]:
# When we don't apply any activation function, the default activation function that will be applied is
# called as linear activation function.
# Now linear activation function is specifically for regression.

# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

# compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

WARNING:tensorflow:From c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 5ms/step - loss: 100387.3125 - mae: 100387.3125 - val_loss: 98551.5234 - val_mae: 98551.5234
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 99753.5781 - mae: 99753.5781 - val_loss: 97265.5312 - val_mae: 97265.5312
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 97503.0547 - mae: 97503.0547 - val_loss: 93950.3516 - val_mae: 93950.3516
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 93005.2422 - mae: 93005.2422 - val_loss: 88299.9375 - val_mae: 88299.9375
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 86298.6875 - mae: 86298.6875 - val_loss: 80745.2109 - val_mae: 80745.2109
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 78057.8984 - mae: 78057.8984 - val_loss: 72376.6719 - val_mae: 72376.6719
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 69570.4922 - mae: 69570.4922 - val_loss: 64564.8594 - val_mae: 64564.8594
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 62156.0430 - mae: 62156.0430 - val_loss: 58341.1992 - val_mae: 58341.1992
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 56617.6211 - mae: 56617.6211 - val_loss: 54107.6016 - val_mae: 54107.6016
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 53161.7070 - mae: 53161.7070 - val_loss: 51867.2852 - val_mae: 51867.2852
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 51386.7031 - mae: 51386.7031 - val_loss: 50978.4492 - val_mae: 50978.4492
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50647.6875 - mae: 50647.6875 - val_loss: 50691.7969 - val_mae: 50691.7969
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50354.2695 - mae: 50354.2695 - val_loss: 50615.2266 - val_mae: 50615.2266
Epoch 14/100
250/250 [==============================] - 2s 6ms/step - loss: 50220.1641 - mae: 50220.1641 - val_loss: 50576.9961 - val_mae: 50576.9961
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 50136.2773 - mae: 50136.2773 - val_loss: 50554.9219 - val_mae: 50554.9219
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50074.0977 - mae: 50074.0977 - val_loss: 50529.7031 - val_mae: 50529.7031
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50025.2109 - mae: 50025.2109 - val_loss: 50503.9453 - val_mae: 50503.9453
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 49982.0039 - mae: 49982.0039 - val_loss: 50478.1758 - val_mae: 50478.1758
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 49942.2188 - mae: 49942.2188 - val_loss: 50447.4961 - val_mae: 50447.4961
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 49909.6172 - mae: 49909.6172 - val_loss: 50429.1992 - val_mae: 50429.1992
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49881.0625 - mae: 49881.0625 - val_loss: 50410.1055 - val_mae: 50410.1055
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49851.4844 - mae: 49851.4844 - val_loss: 50399.7461 - val_mae: 50399.7461
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49829.7617 - mae: 49829.7617 - val_loss: 50376.0625 - val_mae: 50376.0625
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49806.5547 - mae: 49806.5547 - val_loss: 50354.9336 - val_mae: 50354.9336
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49789.2227 - mae: 49789.2227 - val_loss: 50345.9922 - val_mae: 50345.9922
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49764.6562 - mae: 49764.6562 - val_loss: 50346.9062 - val_mae: 50346.9062
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49747.9141 - mae: 49747.9141 - val_loss: 50343.6445 - val_mae: 50343.6445
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49735.7109 - mae: 49735.7109 - val_loss: 50325.4570 - val_mae: 50325.4570
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49711.7656 - mae: 49711.7656 - val_loss: 50321.6211 - val_mae: 50321.6211
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49698.0625 - mae: 49698.0625 - val_loss: 50316.5000 - val_mae: 50316.5000
Epoch 31/100
250/250 [==============================] - 1s 4ms/step - loss: 49680.6953 - mae: 49680.6953 - val_loss: 50318.1055 - val_mae: 50318.1055
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49669.2812 - mae: 49669.2812 - val_loss: 50303.5508 - val_mae: 50303.5508
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49654.7969 - mae: 49654.7969 - val_loss: 50298.3164 - val_mae: 50298.3164
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49644.4961 - mae: 49644.4961 - val_loss: 50294.3008 - val_mae: 50294.3008
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49633.1758 - mae: 49633.1758 - val_loss: 50292.9297 - val_mae: 50292.9297
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49618.6992 - mae: 49618.6992 - val_loss: 50282.6562 - val_mae: 50282.6562
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49611.8711 - mae: 49611.8711 - val_loss: 50279.9102 - val_mae: 50279.9102
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49600.2969 - mae: 49600.2969 - val_loss: 50280.5078 - val_mae: 50280.5078
Epoch 39/100
250/250 [==============================] - 1s 4ms/step - loss: 49587.0703 - mae: 49587.0703 - val_loss: 50275.2305 - val_mae: 50275.2305
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49579.2773 - mae: 49579.2773 - val_loss: 50272.3438 - val_mae: 50272.3438
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 49569.0859 - mae: 49569.0859 - val_loss: 50269.9531 - val_mae: 50269.9531
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49559.3125 - mae: 49559.3125 - val_loss: 50266.2617 - val_mae: 50266.2617
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49552.4688 - mae: 49552.4688 - val_loss: 50265.5664 - val_mae: 50265.5664
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49547.3164 - mae: 49547.3164 - val_loss: 50255.8203 - val_mae: 50255.8203
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49536.8750 - mae: 49536.8750 - val_loss: 50259.9961 - val_mae: 50259.9961
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49526.0781 - mae: 49526.0781 - val_loss: 50254.8164 - val_mae: 50254.8164
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49518.6211 - mae: 49518.6211 - val_loss: 50256.9492 - val_mae: 50256.9492
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49512.2422 - mae: 49512.2422 - val_loss: 50248.4688 - val_mae: 50248.4688
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49504.4023 - mae: 49504.4023 - val_loss: 50254.1875 - val_mae: 50254.1875
Epoch 50/100
250/250 [==============================] - 1s 4ms/step - loss: 49498.1094 - mae: 49498.1094 - val_loss: 50252.8086 - val_mae: 50252.8086
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49494.8320 - mae: 49494.8320 - val_loss: 50248.2812 - val_mae: 50248.2812
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49486.5508 - mae: 49486.5508 - val_loss: 50249.7930 - val_mae: 50249.7930
Epoch 53/100
250/250 [==============================] - 1s 4ms/step - loss: 49478.6641 - mae: 49478.6641 - val_loss: 50251.4453 - val_mae: 50251.4453
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49474.0352 - mae: 49474.0352 - val_loss: 50255.9062 - val_mae: 50255.9062
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49471.5117 - mae: 49471.5117 - val_loss: 50248.6523 - val_mae: 50248.6523
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49461.7305 - mae: 49461.7305 - val_loss: 50252.3047 - val_mae: 50252.3047
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49455.7891 - mae: 49455.7891 - val_loss: 50252.2656 - val_mae: 50252.2656
Epoch 58/100
250/250 [==============================] - 1s 4ms/step - loss: 49451.2539 - mae: 49451.2539 - val_loss: 50250.3555 - val_mae: 50250.3555
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49446.2266 - mae: 49446.2266 - val_loss: 50262.1523 - val_mae: 50262.1523
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49440.4141 - mae: 49440.4141 - val_loss: 50251.5547 - val_mae: 50251.5547
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49434.2930 - mae: 49434.2930 - val_loss: 50259.9414 - val_mae: 50259.9414

In [17]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit --port 6011

In [ ]:
# So let's go ahead and evaluate model on the test data. 
# We're just going to check the accuracy how good it is.
# If more near to zero. If it is going on, we can probably say that our model is pretty trained in an amazing way.
test_loss,test_mae=model.evaluate(x_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 50248.2812 - mae: 50248.2812
Test MAE : 50248.28125
Test loss : 50248.28125

In [ ]:
import numpy as np

mae_percentage = (test_mae / np.mean(y_test)) * 100
print(f"MAE % of target mean: {mae_percentage:.2f}%")

MAE % of target mean: 50.90%

In [23]:
model.save('regression_model.h5')

c:\Users\Nimap\Desktop\ANNProjectImplementation\ann-project-implementation\venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(